### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by lc3t35** [lukaszb/nose-watch#2]
When i launch nosetests with a python script as 

```
python tests/run_suite.py

run_suite.py
    import nose
    nose.main(argv=["noserunner", "--cover-erase", "--with-coverage", "--cover-package=mypackage", "--with-xunit", "--with-watch"])
```

the tests run once and i have the following message

```
Traceback (most recent call last):
  File "tests/run_suite.py", line 20, in <module>
    nose.main(argv=["noserunner", "--cover-erase", "--with-coverage", "--cover-package=mypackage", "--with-xunit", "--with-watch"])
  File "/Library/Python/2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Library/Python/2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Library/Python/2.7/site-packages/nose/core.py", line 68, in run
    self.config.plugins.finalize(result)
  File "/Library/Python/2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Library/Python/2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Library/Python/2.7/site-packages/nosewatch/plugin.py", line 19, in finalize
    argv.remove('--with-watch')
ValueError: list.remove(x): x not in list
```

argv = ['tests/run_suite.py'] :(

**Comment by log0ymxm** [comment]
I'm also seeing the same issue as @CMLL
